#!/usr/bin/python3
# SPDX-FileCopyrightText:2025 YS038
# SPDX-License-Identifier: BSD-3-Clause

import sys

if len(sys.argv) < 2:
    print("Usage: {} KEYWORD", file=sys.stderr)
    sys.exit(1)   # エラー終了（0 以外）

keyword = sys.argv[1]
line_num = 0

for line in sys.stdin:
    if keyword in line:
        line_num += 1
        print(f"{line_num}", end="\n")
