#!/usr/bin/python3
# SPDX-FileCopyrightText:2025 YS038
# SPDX-License-Identifier: BSD-3-Clause

import sys
ans=0.0
for line in sys.stdin:
    try:
      ans+=int(line)
    except:
      ans +=float(line)
print(ans)

#import sys
#ans=sum([float(line)for line in sys.stdin])
#print(ans)
